<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE locale [
    <!ELEMENT locale (message*)>
    <!ATTLIST locale lang CDATA #REQUIRED>
    <!ELEMENT message (id, string)>
    <!ATTLIST message module CDATA #REQUIRED>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT string (#PCDATA)>
    <!ENTITY auml "&amp;auml;">
    <!ENTITY euml "&amp;euml;">
    <!ENTITY iuml "&amp;iuml;">
    <!ENTITY ouml "&amp;ouml;">
    <!ENTITY uuml "&amp;uuml;">
    <!ENTITY Auml "&amp;Auml;">
    <!ENTITY Euml "&amp;Euml;">
    <!ENTITY Auml "&amp;Iuml;">
    <!ENTITY Ouml "&amp;Ouml;">
    <!ENTITY Uuml "&amp;Uuml;">
    <!ENTITY plusmn "&amp;plusmn;">
    <!ENTITY Oslash "&amp;Oslash;">
]>
<locale lang="nl">

   <message module="search_person">
      <id>Person Details</id>
      <string>Persoons Details</string>
   </message>
   <message module="search_person">
      <id>Searched for</id>
      <string>Zoeken naar</string>
   </message>
   <message module="search_person">
      <id>records found in this DVD Collection</id>
      <string>overeenkomsten gevonden in deze Film collectie</string>
   </message>
   <message module="search_person">
      <id>IMDB Search</id>
      <string>IMDB-Zoeken</string>
   </message>
   <message module="search_person">
      <id>Wikipedia Search</id>
      <string>Wikipedia-Zoeken</string>
   </message>
   <message module="search_person">
      <id>OFDB Search</id>
      <string>OFDB-Zoeken</string>
   </message>
   <message module="search_person">
      <id>as</id>
      <string>als</string>
   </message>

   <message module="search">
      <id>Search DVD Collection</id>
      <string>Film collectie doorzoeken</string>
   </message>
   <message module="search">
      <id>Find Movie</id>
      <string>Vind Film</string>
   </message>
   <message module="search">
      <id>Search for Movie</id>
      <string>Zoek op Film</string>
   </message>
   <message module="search">
      <id>Find Person</id>
      <string>Vind Persoon</string>
   </message>
   <message module="search">
      <id>Search for Person</id>
      <string>Zoek op Persoon</string>
   </message>
   <message module="search">
      <id>Add Filters</id>
      <string>Filters toevoegen</string>
   </message>
   <message module="search">
      <id>Genre</id>
      <string>Genre</string>
   </message>
   <message module="search">
      <id>Media Type</id>
      <string>Media Type</string>
   </message>
   <message module="search">
      <id>please select</id>
      <string>selecteer a.u.b.</string>
   </message>
   <message module="search">
      <id>Studio</id>
      <string>Studio</string>
   </message>
   <message module="search">
      <id>Media Company</id>
      <string>Media Maatschappij</string>
   </message>
   <message module="search">
      <id>Tag</id>
      <string>Label</string>
   </message>
   <message module="search">
      <id>Audio Language</id>
      <string>Gesproken Taal</string>
   </message>
   <message module="search">
      <id>Region Code</id>
      <string>Regio Code</string>
   </message>
   <message module="search">
      <id>Remove all filters</id>
      <string>Alle Filters wissen</string>
   </message>

   <message module="start">
      <id>Summary</id>
      <string>Samenvatting</string>
   </message>
   <message module="start">
      <id>News</id>
      <string>Nieuws</string>
   </message>
   <message module="start">
      <id>The %c latest DVDs</id>
      <string>De laatste %c DVD's</string>
   </message>
   <message module="start">
      <id>Cover</id>
      <string>Cover</string>
   </message>
   <message module="start">
      <id>Movie Information</id>
      <string>Film Informatie</string>
   </message>
   <message module="start">
      <id>Purchase Information</id>
      <string>Aankoop Informatie</string>
   </message>
   <message module="start">
      <id>Year of Production</id>
      <string>Produktie jaar</string>
   </message>
   <message module="start">
      <id>Running Time</id>
      <string>Speelduur</string>
   </message>
   <message module="start">
      <id>Minutes</id>
      <string>Minuten</string>
   </message>
   <message module="start">
      <id>Bought</id>
      <string>Gekocht</string>
   </message>
   <message module="start">
      <id>Ordered </id>
      <string>Besteld</string>
   </message>
   <message module="start">
      <id>on</id>
      <string>op</string>
   </message>
   <message module="start">
      <id>Release Date</id>
      <string>Uitgebracht</string>
   </message>
   <message module="start">
      <id>The %c last ordered DVDs</id>
      <string>De laatste %c bestelde DVD's</string>
   </message>
   <message module="start">
      <id>the</id>
      <string>de</string>
   </message>
   <message module="start">
      <id>today</id>
      <string>vandaag</string>
   </message>
   <message module="start">
      <id>Built by</id>
      <string>Gemaakt met</string>
   </message>
   <message module="start">
      <id>published under General Public License (GPL)</id>
      <string>gepubliceerd onder General Public License (GPL)</string>
   </message>
   <message module="start">
      <id>Last update</id>
      <string>Laatste Update</string>
   </message>

   <message module="coverlist">
      <id>Cover Gallery</id>
      <string>Cover Gallerij</string>
   </message>
   <message module="coverlist">
      <id>Number of covers</id>
      <string>Aantal Covers</string>
   </message>

   <message module="top">
      <id>Please activate JavaScript for all functions!</id>
      <string>Activeer Javascript voor alle functies!</string>
   </message>
   <message module="top">
      <id>Home</id>
      <string>Startpagina</string>
   </message>
   <message module="top">
      <id>Search</id>
      <string>Zoeken</string>
   </message>
   <message module="top">
      <id>Administration</id>
      <string>Beheer</string>
   </message>
   <message module="top">
      <id>phpMyProfiler Home</id>
      <string>phpMyProfiler Home</string>
   </message>
   <message module="top">
      <id>phpMyProfiler Forum</id>
      <string>phpMyProfiler Forum</string>
   </message>
   <message module="top">
      <id>Credits</id>
      <string>Credits</string>
   </message>

   <message module="credits">
      <id>Credits - phpMyProfiler</id>
      <string>Credits - phpMyProfiler</string>
   </message>
   <message module="credits">
      <id>Name</id>
      <string>Naam</string>
   </message>
   <message module="credits">
      <id>Nick</id>
      <string>Nick</string>
   </message>
   <message module="credits">
      <id>Developer</id>
      <string>Programmeur</string>
   </message>
   <message module="credits">
      <id>Developer, graphics (till march 2005)</id>
      <string>Programmeur, Grafisch (tot maart 2005)</string>
   </message>
   <message module="credits">
      <id>Developer of myProfiler (till december 2004)</id>
      <string>Programmeur myProfiler (tot december 2004)</string>
   </message>
   <message module="credits">
      <id>Translations</id>
      <string>Vertalingen</string>
   </message>
   <message module="credits">
      <id>Norwegian translation</id>
      <string>Noorse vertaling</string>
   </message>
   <message module="credits">
      <id>Danish translation</id>
      <string>Deense vertaling</string>
   </message>
   <message module="credits">
      <id>Dutch translation</id>
      <string>Nederlandse vertaling</string>
   </message>
   <message module="credits">
      <id>Code contributions</id>
      <string>Code bijdrage</string>
   </message>
   <message module="credits">
      <id>Original parser for DVDProfiler 3.X</id>
      <string>Originele Parser voor DVDProfiler 3.X</string>
   </message>
   <message module="credits">
      <id>Testing, GFX and misc. improvements</id>
      <string>Tester, Grafieken en verschillende Verbeteringen</string>
   </message>
   <message module="credits">
      <id>Used scripts and libraries in phpMyProfiler</id>
      <string>Gebruikte scripts en bibliotheken in phpMyProfiler</string>
   </message>
   <message module="credits">
      <id>Script/library</id>
      <string>Script/Bibliotheek</string>
   </message>
   <message module="credits">
      <id>URL</id>
      <string>URL</string>
   </message>
   <message module="credits">
      <id>License</id>
      <string>Licentie</string>
   </message>
   <message module="credits">
      <id>Icons</id>
      <string>Iconen</string>
   </message>
   <message module="credits">
      <id>All used scripts are liable to the copyright of the corresponding author.</id>
      <string>Alle gebruikte scripts zijn gebonden aan de copyrights van de corresponderende auteurs.</string>
   </message>
   <message module="credits">
      <id>phpMyProfiler is adapted from</id>
      <string>phpMyProfiler is gebasseerd op</string>
   </message>
   <message module="credits">
      <id>by</id>
      <string>van</string>
   </message>

   <message module="picturelist">
      <id>Picture Gallery</id>
      <string>Afbeeldingen Gallerij</string>
   </message>
   <message module="picturelist">
      <id>Number of pictures</id>
      <string>Aantal Afbeeldingen</string>
   </message>

   <message module="filmprofile">
      <id>Features</id>
      <string>Eigenschappen</string>
   </message>
   <message module="filmprofile">
      <id>This DVD is currently loaned</id>
      <string>Deze DVD is momenteel uitgeleend</string>
   </message>
   <message module="filmprofile">
      <id>Details</id>
      <string>Details</string>
   </message>
   <message module="filmprofile">
      <id>Overview</id>
      <string>Overzicht</string>
   </message>
   <message module="filmprofile">
      <id>Cast &amp; Crew</id>
      <string>Cast &amp; Crew</string>
   </message>
   <message module="filmprofile">
      <id>Events</id>
      <string>Uitleenstatus</string>
   </message>
   <message module="filmprofile">
      <id>Episode Guide</id>
      <string>Episode Gids</string>
   </message>
   <message module="filmprofile">
      <id>Cover Images</id>
      <string>Hoesafbeeldingen</string>
   </message>
   <message module="filmprofile">
      <id>Boxset Contents</id>
      <string>Box Set-inhoud</string>
   </message>
   <message module="filmprofile">
      <id>Part of boxset</id>
      <string>Deel van Box Set</string>
   </message>
   <message module="filmprofile">
      <id>External Links</id>
      <string>Externe Links</string>
   </message>
   <message module="filmprofile">
      <id>International</id>
      <string>International</string>
   </message>

   <message module="filmprofile_page1">
      <id>Country of Origin</id>
      <string>Land van herkomst</string>
   </message>
   <message module="filmprofile_page1">
      <id>hrs</id>
      <string>uren</string>
   </message>
   <message module="filmprofile_page1">
      <id>minutes</id>
      <string>minuten</string>
   </message>
   <message module="filmprofile_page1">
      <id>Rating</id>
      <string>Kijkwijzer</string>
   </message>
   <message module="filmprofile_page1">
      <id>Rating Details</id>
      <string>Kijkwijzer Details</string>
   </message>
   <message module="filmprofile_page1">
      <id>Information</id>
      <string>Informatie</string>
   </message>
   <message module="filmprofile_page1">
      <id>Edition</id>
      <string>Editie</string>
   </message>
   <message module="filmprofile_page1">
      <id>ID</id>
      <string>ID</string>
   </message>
   <message module="filmprofile_page1">
      <id>UPC</id>
      <string>EAN</string>
   </message>
   <message module="filmprofile_page1">
      <id>Profile Date</id>
      <string>Profiel Datum</string>
   </message>
   <message module="filmprofile_page1">
      <id>Last Edited</id>
      <string>Laatst bijgewerkt</string>
   </message>
   <message module="filmprofile_page1">
      <id>Country</id>
      <string>Land</string>
   </message>
   <message module="filmprofile_page1">
      <id>Regions</id>
      <string>Regio Code</string>
   </message>
   <message module="filmprofile_page1">
      <id>DVD Release</id>
      <string>Uitgebracht</string>
   </message>
   <message module="filmprofile_page1">
      <id>Case Type</id>
      <string>Soort Doos</string>
   </message>
   <message module="filmprofile_page1">
      <id>Media Companies</id>
      <string>Media bedrijven</string>
   </message>
   <message module="filmprofile_page1">
      <id>Slipcover</id>
      <string>Slipcover</string>
   </message>
   <message module="filmprofile_page1">
      <id>State</id>
      <string>Status</string>
   </message>
   <message module="filmprofile_page1">
      <id>Collection Number</id>
      <string>Collectie nummer</string>
   </message>
   <message module="filmprofile_page1">
      <id>Notes</id>
      <string>Notitie</string>
   </message>
   <message module="filmprofile_page1">
      <id>Purchased</id>
      <string>Gekocht</string>
   </message>
   <message module="filmprofile_page1">
      <id>at</id>
      <string>bij</string>
   </message>
   <message module="filmprofile_page1">
      <id>for</id>
      <string>voor</string>
   </message>
   <message module="filmprofile_page1">
      <id>SRP</id>
      <string>GVP</string>
   </message>
   <message module="filmprofile_page1">
      <id>Rented by</id>
      <string>Uitgeleend aan</string>
   </message>
   <message module="filmprofile_page1">
      <id>Return Date</id>
      <string>Datum retour</string>
   </message>
   <message module="filmprofile_page1">
      <id>Tags</id>
      <string>Labels</string>
   </message>
   <message module="filmprofile_page1">
      <id>Review</id>
      <string>Recensie</string>
   </message>
   <message module="filmprofile_page1">
      <id>Movie</id>
      <string>Film</string>
   </message>
   <message module="filmprofile_page1">
      <id>DVD</id>
      <string>DVD</string>
   </message>
   <message module="filmprofile_page1">
      <id>Audio</id>
      <string>Audio</string>
   </message>
   <message module="filmprofile_page1">
      <id>Extras</id>
      <string>Extras</string>
   </message>
   <message module="filmprofile_page1">
      <id>votes</id>
      <string>Stemmen</string>
   </message>
   <message module="filmprofile_page1">
      <id>Extern Reviews</id>
      <string>Externe Recensies</string>
   </message>
   <message module="filmprofile_page1">
      <id>IMDB User Rating</id>
      <string>IMDB gebruikers waardering</string>
   </message>
   <message module="filmprofile_page1">
      <id>IMDB Top 250</id>
      <string>IMDB Top 250</string>
   </message>
   <message module="filmprofile_page1">
      <id>IMDB Bottom 100</id>
      <string>IMDB Laagste 100</string>
   </message>
   <message module="filmprofile_page1">
      <id>User Reviews</id>
      <string>Recensies van gebruikers</string>
   </message>
   <message module="filmprofile_page1">
      <id>Compose a review</id>
      <string>Schrijf een recensie</string>
   </message>

   <message module="filmprofile_page2">
      <id>Format</id>
      <string>Formaat</string>
   </message>
   <message module="filmprofile_page2">
      <id>Compression</id>
      <string>Compressie</string>
   </message>
   <message module="filmprofile_page2">
      <id>Content</id>
      <string>Taal</string>
   </message>
   <message module="filmprofile_page2">
      <id>Subtitles</id>
      <string>Ondertitels</string>
   </message>
   <message module="filmprofile_page2">
      <id>Video Information</id>
      <string>Video Informatie</string>
   </message>
   <message module="filmprofile_page2">
      <id>Video Format</id>
      <string>Video Standaard</string>
   </message>
   <message module="filmprofile_page2">
      <id>Aspect Ratio</id>
      <string>Beeldverhouding</string>
   </message>
   <message module="filmprofile_page2">
      <id>THX Certified</id>
      <string>THX Gecertiviceerd</string>
   </message>
   <message module="filmprofile_page2">
      <id>Scene Access</id>
      <string>Scenetoegang</string>
   </message>
   <message module="filmprofile_page2">
      <id>Commentary</id>
      <string>Commentaar</string>
   </message>
   <message module="filmprofile_page2">
      <id>Trailers</id>
      <string>Trailers</string>
   </message>
   <message module="filmprofile_page2">
      <id>Deleted Scenes</id>
      <string>Verwijderde Scenes</string>
   </message>
   <message module="filmprofile_page2">
      <id>Featurettes</id>
      <string>Featurettes</string>
   </message>
   <message module="filmprofile_page2">
      <id>Interviews</id>
      <string>Interviews</string>
   </message>
   <message module="filmprofile_page2">
      <id>Storyboard Comparisons</id>
      <string>Storyboard vergelijkingen</string>
   </message>
   <message module="filmprofile_page2">
      <id>DVD-ROM Content</id>
      <string>DVD-ROM Inhoud</string>
   </message>
   <message module="filmprofile_page2">
      <id>Interactive Games</id>
      <string>Interactive Spellen</string>
   </message>
   <message module="filmprofile_page2">
      <id>Multi-angle</id>
      <string>Multi-Hoek</string>
   </message>
   <message module="filmprofile_page2">
      <id>Music Videos</id>
      <string>Muziek Videos</string>
   </message>
   <message module="filmprofile_page2">
      <id>Prod. Notes</id>
      <string>Prod. Notities</string>
   </message>
   <message module="filmprofile_page2">
      <id>Photo Gallery</id>
      <string>Foto Galerij</string>
   </message>
   <message module="filmprofile_page2">
      <id>Outtakes/Bloopers</id>
      <string>Missers/Bloopers</string>
   </message>
   <message module="filmprofile_page2">
      <id>Closed Captioned</id>
      <string>Closed Captioned</string>
   </message>
   <message module="filmprofile_page2">
      <id>Bonus Trailers</id>
      <string>Bonus Trailers</string>
   </message>
   <message module="filmprofile_page2">
      <id>Picture-in-Picture</id>
      <string>Picture-in-Picture</string>
   </message>
   <message module="filmprofile_page2">
      <id>BD-Live</id>
      <string>BD-Live</string>
   </message>
   <message module="filmprofile_page2">
      <id>Digital Copy</id>
      <string>Digital Copy</string>
   </message>
   <message module="filmprofile_page2">
      <id>Other Features</id>
      <string>Overige Features</string>
   </message>
   <message module="filmprofile_page2">
      <id>Additional Information</id>
      <string>Aanvullende Informatie</string>
   </message>
   <message module="filmprofile_page2">
      <id>Studios</id>
      <string>Studios</string>
   </message>
   <message module="filmprofile_page2">
      <id>Genres</id>
      <string>Genres</string>
   </message>
   <message module="filmprofile_page2">
      <id>Media Info</id>
      <string>Media Info</string>
   </message>
   <message module="filmprofile_page2">
      <id>Description Side A</id>
      <string>Beschrijving Kant A</string>
   </message>
   <message module="filmprofile_page2">
      <id>Label Side A</id>
      <string>Label Kant A</string>
   </message>
   <message module="filmprofile_page2">
      <id>Duallayer Side A</id>
      <string>Duallayer Kant A</string>
   </message>
   <message module="filmprofile_page2">
      <id>DiscID Side A</id>
      <string>DiscID Kant A</string>
   </message>
   <message module="filmprofile_page2">
      <id>Description Side B</id>
      <string>Beschrijving Kant B</string>
   </message>
   <message module="filmprofile_page2">
      <id>Label Side B</id>
      <string>Label Kant B</string>
   </message>
   <message module="filmprofile_page2">
      <id>DiscID Side B</id>
      <string>DiscID Kant B</string>
   </message>
   <message module="filmprofile_page2">
      <id>Duallayer Side B</id>
      <string>Duallayer Kant B</string>
   </message>
   <message module="filmprofile_page2">
      <id>Dualsided</id>
      <string>Dubbelzijdig</string>
   </message>
   <message module="filmprofile_page2">
      <id>Dual Layered</id>
      <string>Dubbellaags</string>
   </message>
   <message module="filmprofile_page2">
      <id>Single Layered</id>
      <string>Enkellaags</string>
   </message>
   <message module="filmprofile_page2">
      <id>Location</id>
      <string>Locatie</string>
   </message>
   <message module="filmprofile_page2">
      <id>Slot</id>
      <string>Slot</string>
   </message>
   <message module="filmprofile_page2">
      <id>Various Information</id>
      <string>Overige Informatie</string>
   </message>
   <message module="filmprofile_page2">
      <id>Easter Egg</id>
      <string>Easter Egg</string>
   </message>
   <message module="filmprofile_page2">
      <id>Awards</id>
      <string>Awards</string>
   </message>
   <message module="filmprofile_page2">
      <id>Winner</id>
      <string>Winnaar</string>
   </message>
   <message module="filmprofile_page2">
      <id>Nominee for</id>
      <string>Genomineerd voor</string>
   </message>

   <message module="filmprofile_page3">
      <id>Cast</id>
      <string>Cast</string>
   </message>
   <message module="filmprofile_page3">
      <id>uncredited</id>
      <string>Niet genoemd</string>
   </message>
   <message module="filmprofile_page3">
      <id>voice</id>
      <string>Stemmen</string>
   </message>
   <message module="filmprofile_page3">
      <id>credited as</id>
      <string>credited as</string>
   </message>
   <message module="filmprofile_page3">
      <id>Crew</id>
      <string>Crew</string>
   </message>

   <message module="filmprofile_page4">
      <id>Date</id>
      <string>Datum</string>
   </message>
   <message module="filmprofile_page4">
      <id>Event</id>
      <string>Uitleenstatus</string>
   </message>
   <message module="filmprofile_page4">
      <id>Phone</id>
      <string>Telefoon</string>
   </message>
   <message module="filmprofile_page4">
      <id>Borrowed</id>
      <string>Uitgeleend</string>
   </message>
   <message module="filmprofile_page4">
      <id>Returned</id>
      <string>Terug</string>
   </message>

   <message module="filmprofile_status">
      <id>Owned</id>
      <string>In bezit</string>
   </message>
   <message module="filmprofile_status">
      <id>Ordered</id>
      <string>Besteld</string>
   </message>
   <message module="filmprofile_status">
      <id>WishList</id>
      <string>Verlanglijst</string>
   </message>

   <message module="filmprofile_wishpriority">
      <id>Vague Interest</id>
      <string>Vage Interesse</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Like to Have It</id>
      <string>Leuk te hebben</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Want It</id>
      <string>Wil ik hebben</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Really Want</id>
      <string>Moet ik hebben</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Need It</id>
      <string>Kan niet zonder</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Watched</id>
      <string>Gezien</string>
   </message>

   <message module="statistics">
      <id>Statistics</id>
      <string>Statistieken</string>
   </message>
   <message module="statistics">
      <id>Other Statistics</id>
      <string>Andere Statistieken</string>
   </message>
   <message module="statistics">
      <id>Director Statistic</id>
      <string>Regisseurs</string>
   </message>
   <message module="statistics">
      <id>Producer Statistic</id>
      <string>Producenten</string>
   </message>
   <message module="statistics">
      <id>Writer &amp; Screenwriter Statistic</id>
      <string>Auteurs &amp; Scriptschrijvers</string>
   </message>
   <message module="statistics">
      <id>Composer Statistic</id>
      <string>Componisten</string>
   </message>
   <message module="statistics">
      <id>Actor Statistic</id>
      <string>Acteurs</string>
   </message>
   <message module="statistics">
      <id>Number of DVDs</id>
      <string>Aantal DVD's</string>
   </message>
   <message module="statistics">
      <id>With Pricing Information</id>
      <string>DVD's met Prijsinfo</string>
   </message>
   <message module="statistics">
      <id>DVDs without a Child Profile</id>
      <string>DVD's zonder kinder Profiel</string>
   </message>
   <message module="statistics">
      <id>Boxset Profiles</id>
      <string>Box Set Profiel</string>
   </message>
   <message module="statistics">
      <id>Child Profiles</id>
      <string>Kinder Profiel</string>
   </message>
   <message module="statistics">
      <id>DVDs with Collection Number</id>
      <string>DVD's met Collectie Nummer</string>
   </message>
   <message module="statistics">
      <id>DVDs with Rating Information</id>
      <string>DVD's met Kijkwijzer Informatie</string>
   </message>
   <message module="statistics">
      <id>Price of all DVDs</id>
      <string>Prijs van alle DVD's</string>
   </message>
   <message module="statistics">
      <id>Average price</id>
      <string>Gemiddelde prijs</string>
   </message>
   <message module="statistics">
      <id>Most expensive DVDs</id>
      <string>De duurste DVD's</string>
   </message>
   <message module="statistics">
      <id>Cheapest DVDs</id>
      <string>De goedkoopste DVD's</string>
   </message>
   <message module="statistics">
      <id>Length of all DVDs</id>
      <string>Gezamelijke speelduur</string>
   </message>
   <message module="statistics">
      <id>DVDs with Length Information</id>
      <string>DVD's met opgegeven speelduur</string>
   </message>
   <message module="statistics">
      <id>Hours: about</id>
      <string>&plusmn;
      </string>
   </message>
   <message module="statistics">
      <id>hours</id>
      <string>uur</string>
   </message>
   <message module="statistics">
      <id>Days: about</id>
      <string>&plusmn;
      </string>
   </message>
   <message module="statistics">
      <id>days</id>
      <string>dagen</string>
   </message>
   <message module="statistics">
      <id>Weeks: about</id>
      <string>&plusmn;
      </string>
   </message>
   <message module="statistics">
      <id>weeks</id>
      <string>weken</string>
   </message>
   <message module="statistics">
      <id>Months: about</id>
      <string>&plusmn;
      </string>
   </message>
   <message module="statistics">
      <id>months</id>
      <string>maanden</string>
   </message>
   <message module="statistics">
      <id>Years: about</id>
      <string>&plusmn;
      </string>
   </message>
   <message module="statistics">
      <id>years</id>
      <string>jaar</string>
   </message>
   <message module="statistik">
      <id>Average Length</id>
      <string>Gemiddelde speelduur</string>
   </message>
   <message module="statistics">
      <id>Longest DVDs</id>
      <string>De DVD's met de langste speelduur</string>
   </message>
   <message module="statistics">
      <id>Shortest DVDs</id>
      <string>De DVD's met de kortste speelduur</string>
   </message>
   <message module="statistics">
      <id>Regioncode</id>
      <string>Regio code</string>
   </message>
   <message module="statistics">
      <id>Localities of DVDs</id>
      <string>Herkomst van de DVD's</string>
   </message>
   <message module="statistics">
      <id>Localities</id>
      <string>Landen</string>
   </message>
   <message module="statistics">
      <id>Origins of Movies</id>
      <string>Land van Productie</string>
   </message>
   <message module="statistics">
      <id>Origins</id>
      <string>Orgineel</string>
   </message>
   <message module="statistics">
      <id>Ratings</id>
      <string>Kijkwijzer</string>
   </message>
   <message module="statistics">
      <id>DVDs</id>
      <string>DVD's</string>
   </message>
   <message module="statistics">
      <id>Year of Purchase</id>
      <string>Jaar van aankoop</string>
   </message>
   <message module="statistics">
      <id>Detailed Statistic</id>
      <string>Gedetaileerde Statistiek</string>
   </message>
   <message module="statistics">
      <id>Production Decade</id>
      <string>Produktieperiode</string>
   </message>
   <message module="statistics">
      <id>Place of Purchase (Top 10)</id>
      <string>Gekocht bij (Top 10)</string>
   </message>
   <message module="statistics">
      <id>Place of Purchase</id>
      <string>Gekocht bij</string>
   </message>
   <message module="statistics">
      <id>Genre (Top 10)</id>
      <string>Genre (Top 10)</string>
   </message>
   <message module="statistics">
      <id>Studio (Top 10)</id>
      <string>Studio (Top 10)</string>
   </message>
   <message module="statistics">
      <id>Media Companies (Top 10)</id>
      <string>Media Maatschappijen (Top 10)</string>
   </message>
   <message module="statistics">
      <id>Visitors</id>
      <string>Bezoekers</string>
   </message>
   <message module="statistics">
      <id>Visited DVDs</id>
      <string>Bezochte DVD-Profielen</string>
   </message>

   <message module="statistics_graph">
      <id>owned</id>
      <string>In bezit</string>
   </message>
   <message module="statistics_graph">
      <id>ordered</id>
      <string>Besteld</string>
   </message>
   <message module="statistics_graph">
      <id>wishlist</id>
      <string>Verlanglijst</string>
   </message>

   <message module="statisticsdetail">
      <id>Visitor Statistic</id>
      <string>Bezoekers Statistiek</string>
   </message>
   <message module="statisticsdetail">
      <id>Profile Statistic</id>
      <string>Profiel Statistiek</string>
   </message>
   <message module="statisticsdetail">
      <id>Result</id>
      <string>Resultaat</string>
   </message>
   <message module="statisticsdetail">
      <id>Month</id>
      <string>Maand</string>
   </message>
   <message module="statisticsdetail">
      <id>January</id>
      <string>Januari</string>
   </message>
   <message module="statisticsdetail">
      <id>February</id>
      <string>Februari</string>
   </message>