<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE locale [
    <!ELEMENT locale (message*)>
    <!ATTLIST locale
    	lang CDATA #REQUIRED
    >
    <!ELEMENT message (id, string)>
    <!ATTLIST message
    	module CDATA #REQUIRED
    >
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT string (#PCDATA)>
    <!ENTITY aelig "&amp;aelig;">
    <!ENTITY AElig "&amp;AElig;">
    <!ENTITY aring "&amp;aring;">
    <!ENTITY Aring "&amp;Aring;">
    <!ENTITY oslash "&amp;oslash;">
    <!ENTITY Oslash "&amp;Oslash;">
]>
<locale lang="dk">

  <message module="search_person">
    <id>Person Details</id>
    <string>Person Detajler</string>
  </message>
  <message module="search_person">
    <id>Searched for</id>
    <string>S&oslash;gning efter</string>
  </message>
  <message module="search_person">
    <id>records found in this DVD Collection</id>
    <string>film fundet i denne DVD samling</string>
  </message>
  <message module="search_person">
    <id>IMDB Search</id>
    <string>IMDB-S&oslash;gning</string>
  </message>
  <message module="search_person">
    <id>Wikipedia Search</id>
    <string>S&oslash;g i Wikipedia</string>
  </message>
  <message module="search_person">
    <id>OFDB Search</id>
    <string>OFDB-S&oslash;gning</string>
  </message>
  <message module="search_person">
    <id>as</id>
    <string>som</string>
  </message>

  <message module="search">
    <id>Search DVD Collection</id>
    <string>S&oslash;g i DVD Samlingen</string>
  </message>
  <message module="search">
    <id>Find Movie</id>
    <string>Find Film</string>
  </message>
  <message module="search">
    <id>Search for Movie</id>
    <string>S&oslash;g Efter Film</string>
  </message>
  <message module="search">
    <id>Find Person</id>
    <string>Find Person</string>
  </message>
  <message module="search">
    <id>Search for Person</id>
    <string>S&oslash;g Efter Person</string>
  </message>
  <message module="search">
    <id>Add Filters</id>
    <string>Tilf&oslash;j Filter</string>
  </message>
  <message module="search">
    <id>Genre</id>
    <string>Genre</string>
  </message>
  <message module="search">
    <id>Media Type</id>
    <string>Media Type</string>
  </message>
  <message module="search">
    <id>please select</id>
    <string>v&aelig;lg venligst</string>
  </message>
  <message module="search">
    <id>Studio</id>
    <string>Studio</string>
  </message>
  <message module="search">
    <id>Media Company</id>
    <string>Media Virksomhed</string>
  </message>
  <message module="search">
    <id>Tag</id>
    <string>Tag</string>
  </message>
  <message module="search">
    <id>Audio Language</id>
    <string>Talte Sprog</string>
  </message>
  <message module="search">
    <id>Region Code</id>
    <string>Regions Kode</string>
  </message>
  <message module="search">
    <id>Remove all filters</id>
    <string>Fjern Alle Filtre</string>
  </message>

  <message module="start">
    <id>Summary</id>
    <string>Oversigt</string>
  </message>
  <message module="start">
    <id>News</id>
    <string>Nyheder</string>
  </message>
  <message module="start">
    <id>The %c latest DVDs</id>
    <string>De %c Nyeste DVDer</string>
  </message>
  <message module="start">
    <id>Cover</id>
    <string>Omslag</string>
  </message>
  <message module="start">
    <id>Movie Information</id>
    <string>Film Information</string>
  </message>
  <message module="start">
    <id>Purchase Information</id>
    <string>K&oslash;bs Information</string>
  </message>
  <message module="start">
    <id>Year of Production</id>
    <string>Produktions&aring;r</string>
  </message>
  <message module="start">
    <id>Running Time</id>
    <string>Spilletid</string>
  </message>
  <message module="start">
    <id>Minutes</id>
    <string>Minutter</string>
  </message>
  <message module="start">
    <id>Bought</id>
    <string>K&oslash;bt</string>
  </message>
  <message module="start">
    <id>Ordered </id>
    <string>Bestilt </string>
  </message>
  <message module="start">
    <id>on</id>
    <string>den</string>
  </message>
  <message module="start">
    <id>Release Date</id>
    <string>Udgivelsesdato</string>
  </message>
  <message module="start">
    <id>The %c last ordered DVDs</id>
    <string>De %c sidst bestilte DVDer</string>
  </message>
  <message module="start">
    <id>the</id>
    <string>den</string>
  </message>
  <message module="start">
    <id>today</id>
    <string>idag</string>
  </message>
  <message module="start">
    <id>Built by</id>
    <string>Bygget af</string>
  </message>
  <message module="start">
    <id>published under General Public License (GPL)</id>
    <string>Udgivet under General Public License (GPL)</string>
  </message>
  <message module="start">
    <id>Last update</id>
    <string>Sidste opdatering</string>
  </message>

  <message module="coverlist">
    <id>Cover Gallery</id>
    <string>Omslagsgalleri</string>
  </message>
  <message module="coverlist">
    <id>Number of covers</id>
    <string>Antal omslag</string>
  </message>

  <message module="top">
    <id>Please activate JavaScript for all functions!</id>
    <string>Aktiver venligst Java Script, for alle funktioner skal fungere!</string>
  </message>
  <message module="top">
    <id>Home</id>
    <string>Startside</string>
  </message>
  <message module="top">
    <id>Search</id>
    <string>S&oslash;g</string>
  </message>
  <message module="top">
    <id>Administration</id>
    <string>Adminstration</string>
  </message>
  <message module="top">
    <id>phpMyProfiler Home</id>
    <string>phpMyProfiler Home</string>
  </message>
  <message module="top">
    <id>phpMyProfiler Forum</id>
    <string>phpMyProfiler Forum</string>
  </message>
  <message module="top">
    <id>Credits</id>
    <string>Credits</string>
  </message>

  <message module="credits">
    <id>Credits - phpMyProfiler</id>
    <string>Credits - phpMyProfiler</string>
  </message>
  <message module="credits">
    <id>Name</id>
    <string>Navn</string>
  </message>
  <message module="credits">
    <id>Nick</id>
    <string>Nick</string>
  </message>
  <message module="credits">
    <id>Developer</id>
    <string>Programm&oslash;r</string>
  </message>
  <message module="credits">
    <id>Developer, graphics (till march 2005)</id>
    <string>Grafisk Programm&oslash;r (indtil Marts 2005)</string>
  </message>
  <message module="credits">
    <id>Developer of myProfiler (till december 2004)</id>
    <string>Programm&oslash;r af myProfiler (indtil December 2004)</string>
  </message>
  <message module="credits">
    <id>Translations</id>
    <string>Overs&aelig;ttelser</string>
  </message>
  <message module="credits">
    <id>Norweigan translation</id>
    <string>Norsk overs&aelig;ttelse</string>
  </message>
  <message module="credits">
    <id>Danish translation</id>
    <string>Dansk overs&aelig;ttelse</string>
  </message>
  <message module="credits">
    <id>Dutch translation</id>
    <string>Hollandsk overs&aelig;ttelse</string>
  </message>
  <message module="credits">
    <id>Code contributions</id>
    <string>Kode bidrag</string>
  </message>
  <message module="credits">
    <id>Original parser for DVDProfiler 3.X</id>
    <string>Original Parser for DVDProfiler 3.X</string>
  </message>
  <message module="credits">
    <id>Testing, GFX and misc. improvements</id>
    <string>Tester, Grafik og div forbedringer</string>
  </message>
  <message module="credits">
    <id>Used scripts and libraries in phpMyProfiler</id>
    <string>Brugte scripts og biblioteker i phpMyProfiler</string>
  </message>
  <message module="credits">
    <id>Script/library</id>
    <string>Script/Bibliotek</string>
  </message>
  <message module="credits">
    <id>URL</id>
    <string>URL</string>
  </message>
  <message module="credits">
    <id>License</id>
    <string>Licens</string>
  </message>
  <message module="credits">
    <id>Icons</id>
    <string>Ikoner</string>
  </message>
  <message module="credits">
    <id>All used scripts are liable to the copyright of the corresponding author.</id>
    <string>Alle brugte scripts h&oslash;rer under den p&aring;g&aelig;ldende ejers copyright.</string>
  </message>
  <message module="credits">
    <id>phpMyProfiler is adapted from</id>
    <string>phpMyProfiler er baseret p&aring;</string>
  </message>
  <message module="credits">
    <id>by</id>
    <string>af</string>
  </message>

  <message module="picturelist">
    <id>Picture Gallery</id>
    <string>Foto Galleri</string>
  </message>
  <message module="picturelist">
    <id>Number of pictures</id>
    <string>Antal billeder</string>
  </message>

  <message module="filmprofile">
    <id>Features</id>
    <string>Indhold</string>
  </message>
  <message module="filmprofile">
    <id>This DVD is currently loaned</id>
    <string>Denne DVD er i &oslash;jeblikket udl&aring;nt</string>
  </message>
  <message module="filmprofile">
    <id>Details</id>
    <string>Detajler</string>
  </message>
  <message module="filmprofile">
    <id>Overview</id>
    <string>Oversigt</string>
  </message>
  <message module="filmprofile">
    <id>Cast &amp; Crew</id>
    <string>Skuespillere &amp; Filmhold</string>
  </message>
  <message module="filmprofile">
    <id>Events</id>
    <string>Status</string>
  </message>
  <message module="filmprofile">
    <id>Episode Guide</id>
    <string>Episode Guide</string>
  </message>
  <message module="filmprofile">
    <id>Cover Images</id>
    <string>Omslagsbilleder</string>
  </message>
  <message module="filmprofile">
    <id>Boxset Contents</id>
    <string>Bokss&aelig;t Indhold</string>
  </message>
  <message module="filmprofile">
    <id>Part of boxset</id>
    <string>En del af et boks s&aelig;t</string>
  </message>
  <message module="filmprofile">
    <id>External Links</id>
    <string>Ekstern Links</string>
  </message>
  <message module="filmprofile">
    <id>International</id>
    <string>International</string>
  </message>

  <message module="filmprofile_page1">
    <id>Country of Origin</id>
    <string>Ophavsland</string>
  </message>
  <message module="filmprofile_page1">
    <id>hrs</id>
    <string>Timer</string>
  </message>
  <message module="filmprofile_page1">
    <id>minutes</id>
    <string>Minutter</string>
  </message>
  <message module="filmprofile_page1">
    <id>Rating</id>
    <string>Score</string>
  </message>
  <message module="filmprofile_page1">
    <id>Rating Details</id>
    <string>Score Detajler</string>
  </message>
  <message module="filmprofile_page1">
    <id>Information</id>
    <string>Information</string>
  </message>
  <message module="filmprofile_page1">
    <id>Edition</id>
    <string>Udgave</string>
  </message>
  <message module="filmprofile_page1">
    <id>ID</id>
    <string>ID</string>
  </message>
  <message module="filmprofile_page1">
    <id>UPC</id>
    <string>EAN</string>
  </message>
  <message module="filmprofile_page1">
    <id>Profile Date</id>
    <string>Profil dato</string>
  </message>
  <message module="filmprofile_page1">
    <id>Last Edited</id>
    <string>Sidst redigeret</string>
  </message>
  <message module="filmprofile_page1">
    <id>Country</id>
    <string>Land</string>
  </message>
  <message module="filmprofile_page1">
    <id>Regions</id>
    <string>Regioner</string>
  </message>
  <message module="filmprofile_page1">
    <id>DVD Release</id>
    <string>DVD Udgivelse</string>
  </message>
  <message module="filmprofile_page1">
    <id>Case Type</id>
    <string>Omslagstype</string>
  </message>
  <message module="filmprofile_page1">
    <id>Media Companies</id>
    <string>Media Firmaer</string>
  </message>
  <message module="filmprofile_page1">
    <id>Slipcover</id>
    <string>Slipcover</string>
  </message>
  <message module="filmprofile_page1">
    <id>State</id>
    <string>Status</string>
  </message>
  <message module="filmprofile_page1">
    <id>Collection Number</id>
    <string>Samlingsnummer</string>
  </message>
  <message module="filmprofile_page1">
    <id>Notes</id>
    <string>Noter</string>
  </message>
  <message module="filmprofile_page1">
    <id>Purchased</id>
    <string>K&oslash;bt</string>
  </message>
  <message module="filmprofile_page1">
    <id>at</id>
    <string>hos</string>
  </message>
  <message module="filmprofile_page1">
    <id>for</id>
    <string>for</string>
  </message>
  <message module="filmprofile_page1">
    <id>SRP</id>
    <string>UVP</string>
  </message>
  <message module="filmprofile_page1">
    <id>Rented by</id>
    <string>Udl&aring;nt til</string>
  </message>
  <message module="filmprofile_page1">
    <id>Return Date</id>
    <string>Afleveringsdato</string>
  </message>
  <message module="filmprofile_page1">
    <id>Tags</id>
    <string>Tags</string>
  </message>
  <message module="filmprofile_page1">
    <id>Review</id>
    <string>Anmeldelse</string>
  </message>
  <message module="filmprofile_page1">
    <id>Movie</id>
    <string>Film</string>
  </message>
  <message module="filmprofile_page1">
    <id>DVD</id>
    <string>DVD</string>
  </message>
  <message module="filmprofile_page1">
    <id>Audio</id>
    <string>Lyd</string>
  </message>
  <message module="filmprofile_page1">
    <id>Extras</id>
    <string>Ekstra materiale</string>
  </message>
  <message module="filmprofile_page1">
    <id>votes</id>
    <string>Stemmer</string>
  </message>
  <message module="filmprofile_page1">
    <id>Extern Reviews</id>
    <string>Eksterne anmeldelser</string>
  </message>
  <message module="filmprofile_page1">
    <id>IMDB User Rating</id>
    <string>IMDB Bruger Rating</string>
  </message>
  <message module="filmprofile_page1">
    <id>IMDB Top 250</id>
    <string>IMDB Top 250</string>
  </message>
  <message module="filmprofile_page1">
    <id>IMDB Bottom 100</id>
    <string>100 d&aring;rligeste film p&aring; IMDB</string>
  </message>
  <message module="filmprofile_page1">
    <id>User Reviews</id>
    <string>Bruger anmeldelser</string>
  </message>
  <message module="filmprofile_page1">
    <id>Compose a review</id>
    <string>Skriv en anmeldelse</string>
  </message>

  <message module="filmprofile_page2">
    <id>Format</id>
    <string>Format</string>
  </message>
  <message module="filmprofile_page2">
    <id>Compression</id>
    <string>Komprimering</string>
  </message>
  <message module="filmprofile_page2">
    <id>Content</id>
    <string>Indhold</string>
  </message>
  <message module="filmprofile_page2">
    <id>Subtitles</id>
    <string>Untertekster</string>
  </message>
  <message module="filmprofile_page2">
    <id>Video Information</id>
    <string>Videoinformation</string>
  </message>
  <message module="filmprofile_page2">
    <id>Video Format</id>
    <string>Video Format</string>
  </message>
  <message module="filmprofile_page2">
    <id>Aspect Ratio</id>
    <string>Billed Forhold</string>
  </message>
  <message module="filmprofile_page2">
    <id>THX Certified</id>
    <string>THX certificeret</string>
  </message>
  <message module="filmprofile_page2">
    <id>Scene Access</id>
    <string>Scene Adgang</string>
  </message>
  <message module="filmprofile_page2">
    <id>Commentary</id>
    <string>Kommentar</string>
  </message>
  <message module="filmprofile_page2">
    <id>Trailers</id>
    <string>Trailere</string>
  </message>
  <message module="filmprofile_page2">
    <id>Deleted Scenes</id>
    <string>Slettede Scener</string>
  </message>
  <message module="filmprofile_page2">
    <id>Featurettes</id>
    <string>Featurettes</string>
  </message>
  <message module="filmprofile_page2">
    <id>Interviews</id>
    <string>Interviews</string>
  </message>
  <message module="filmprofile_page2">
    <id>Storyboard Comparisons</id>
    <string>Storyboard Comparisons</string>
  </message>
  <message module="filmprofile_page2">
    <id>DVD-ROM Content</id>
    <string>DVD-ROM Indhold</string>
  </message>
  <message module="filmprofile_page2">
    <id>Interactive Games</id>
    <string>Interaktive Spil</string>
  </message>
  <message module="filmprofile_page2">
    <id>Multi-angle</id>
    <string>Multi-Angle</string>
  </message>
  <message module="filmprofile_page2">
    <id>Music Videos</id>
    <string>Musikvideoer</string>
  </message>
  <message module="filmprofile_page2">
    <id>Prod. Notes</id>
    <string>Prod. Noter</string>
  </message>
  <message module="filmprofile_page2">
    <id>Photo Gallery</id>
    <string>Billed Galleri</string>
  </message>
  <message module="filmprofile_page2">
    <id>Outtakes/Bloopers</id>
    <string>Fraklippede Scener/Smuttere</string>
  </message>
  <message module="filmprofile_page2">
    <id>Closed Captioned</id>
    <string>Closed Captioned</string>
  </message>
  <message module="filmprofile_page2">
    <id>Bonus Trailers</id>
    <string>Bonus Trailere</string>
  </message>
  <message module="filmprofile_page2">
    <id>Picture-in-Picture</id>
    <string>Picture-in-Picture</string>
  </message>
  <message module="filmprofile_page2">
    <id>BD-Live</id>
    <string>BD-Live</string>
  </message>
  <message module="filmprofile_page2">
    <id>Digital Copy</id>
    <string>Digital Kopi</string>
  </message>
  <message module="filmprofile_page2">
    <id>Other Features</id>
    <string>Andet Indhold</string>
  </message>
  <message module="filmprofile_page2">
    <id>Additional Information</id>
    <string>Yderligere Informationen</string>
  </message>
  <message module="filmprofile_page2">
    <id>Studios</id>
    <string>Studier</string>
  </message>
  <message module="filmprofile_page2">
    <id>Genres</id>
    <string>Genre</string>
  </message>
  <message module="filmprofile_page2">
    <id>Media Info</id>
    <string>Medie Info</string>
  </message>
  <message module="filmprofile_page2">
    <id>Description Side A</id>
    <string>Beskrivelse Side A</string>
  </message>
  <message module="filmprofile_page2">
    <id>Label Side A</id>
    <string>Merkat Side A</string>
  </message>
  <message module="filmprofile_page2">
    <id>Duallayer Side A</id>
    <string>Duallayer Side A</string>
  </message>
  <message module="filmprofile_page2">
    <id>DiscID Side A</id>
    <string>Disk-ID Side A</string>
  </message>
  <message module="filmprofile_page2">
    <id>Description Side B</id>
    <string>Beskrivelse Side B</string>
  </message>
  <message module="filmprofile_page2">
    <id>Label Side B</id>
    <string>Merkat Side B</string>
  </message>
  <message module="filmprofile_page2">
    <id>DiscID Side B</id>
    <string>Disk-ID Side B</string>
  </message>
  <message module="filmprofile_page2">
    <id>Duallayer Side B</id>
    <string>Duallayer Side B</string>
  </message>
  <message module="filmprofile_page2">
    <id>Dualsided</id>
    <string>Dualsided</string>
  </message>
  <message module="filmprofile_page2">
    <id>Dual Layered</id>
    <string>Dobbeltlag</string>
  </message>
  <message module="filmprofile_page2">
    <id>Single Layered</id>
    <string>Enkeltlag</string>
  </message>
  <message module="filmprofile_page2">
    <id>Location</id>
    <string>Sted</string>
  </message>
  <message module="filmprofile_page2">
    <id>Slot</id>
    <string>Slot</string>
  </message>
  <message module="filmprofile_page2">
    <id>Various Information</id>
    <string>Diverse Information</string>
  </message>
  <message module="filmprofile_page2">
    <id>Easter Egg</id>
    <string>P&aring;ske &aelig;g</string>
  </message>
  <message module="filmprofile_page2">
    <id>Awards</id>
    <string>Film Priser</string>
  </message>
  <message module="filmprofile_page2">
    <id>Winner</id>
    <string>Vinder</string>
  </message>
  <message module="filmprofile_page2">
    <id>Nominee for</id>
    <string>Nominerede</string>
  </message>

  <message module="filmprofile_page3">
    <id>Cast</id>
    <string>Medvirkende</string>
  </message>
  <message module="filmprofile_page3">
    <id>uncredited</id>
    <string>Ikke krediteret</string>
  </message>
  <message module="filmprofile_page3">
    <id>voice</id>
    <string>Stemme</string>
  </message>
  <message module="filmprofile_page3">
    <id>credited as</id>
    <string>Krediteret som</string>
  </message>
  <message module="filmprofile_page3">
    <id>Crew</id>
    <string>Filmhold</string>
  </message>

  <message module="filmprofile_page4">
    <id>Date</id>
    <string>Dato</string>
  </message>
  <message module="filmprofile_page4">
    <id>Event</id>
    <string>Event</string>
  </message>
  <message module="filmprofile_page4">
    <id>Phone</id>
    <string>Telefon</string>
  </message>
  <message module="filmprofile_page4">
    <id>Borrowed</id>
    <string>L&aring;nt</string>
  </message>
  <message module="filmprofile_page4">
    <id>Returned</id>
    <string>Returneret</string>
  </message>

  <message module="filmprofile_status">
    <id>Owned</id>
    <string>Egne DVDer</string>
  </message>
  <message module="filmprofile_status">
    <id>Ordered</id>
    <string>Bestilte DVDer</string>
  </message>
  <message module="filmprofile_status">
    <id>WishList</id>
    <string>&oslash;nskeliste</string>
  </message>

  <message module="filmprofile_wishpriority">
    <id>Vague Interest</id>
    <string>Svag Interesse</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Like to Have It</id>
    <string>Vil gerne have</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Want It</id>
    <string>Vil have den</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Really Want</id>
    <string>Virkelig gerne have den</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Need It</id>
    <string>Skal have den</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Watched</id>
    <string>Set</string>
  </message>

  <message module="statistics">
    <id>Statistics</id>
    <string>Statistikker</string>
  </message>
  <message module="statistics">
    <id>Other Statistics</id>
    <string>Andre Statistikker</string>
  </message>
  <message module="statistics">
    <id>Director Statistic</id>
    <string>Instrukt&oslash;r statistik</string>
  </message>
  <message module="statistics">
    <id>Producer Statistic</id>
    <string>Producent statistik</string>
  </message>
  <message module="statistics">
    <id>Writer &amp; Screenwriter Statistic</id>
    <string>Forfatter statistik</string>
  </message>
  <message module="statistics">
    <id>Composer Statistic</id>
    <string>Composer Statistikker</string>
  </message>
  <message module="statistics">
    <id>Actor Statistic</id>
    <string>Skuespiller rstatistik</string>
  </message>
  <message module="statistics">
    <id>Number of DVDs</id>
    <string>Antal DVDer</string>
  </message>
  <message module="statistics">
    <id>With Pricing Information</id>
    <string>DVDer med prisinformation</string>
  </message>
  <message module="statistics">
    <id>DVDs without a Child Profile</id>
    <string>DVDer uden b&oslash;rne profiler</string>
  </message>
  <message module="statistics">
    <id>Boxset Profiles</id>
    <string>Bokss&aelig;t Profiler</string>
  </message>
  <message module="statistics">
    <id>Child Profiles</id>
    <string>B&aelig;rne Profiler</string>
  </message>
  <message module="statistics">
    <id>DVDs with Collection Number</id>
    <string>DVDer med Samlingsnummer</string>
  </message>
  <message module="statistics">
    <id>DVDs with Rating Information</id>
    <string>DVDer med Rating information</string>
  </message>
  <message module="statistics">
    <id>Price of all DVDs</id>
    <string>Samlet pris for alle DVDer</string>
  </message>
  <message module="statistics">
    <id>Average price</id>
    <string>Gennemsnitspris</string>
  </message>
  <message module="statistics">
    <id>Most expensive DVDs</id>
    <string>De dyreste DVDer</string>
  </message>
  <message module="statistics">
    <id>Cheapest DVDs</id>
    <string>De billigste DVDer</string>
  </message>
  <message module="statistics">
    <id>Length of all DVDs</id>
    <string>Samlet l&aelig;ngde af alle DVDer</string>
  </message>
  <message module="statistics">
    <id>DVDs with Length Information</id>
    <string>DVDer med l&aelig;ngde information</string>
  </message>
  <message module="statistics">
    <id>Hours: about</id>
    <string>Timer: ca.</string>
  </message>
  <message module="statistics">
    <id>hours</id>
    <string>Timer</string>
  </message>
  <message module="statistics">
    <id>Days: about</id>
    <string>Dage: ca.</string>
  </message>
  <message module="statistics">
    <id>days</id>
    <string>dage</string>
  </message>
  <message module="statistics">
    <id>Weeks: about</id>
    <string>Uger: ca.</string>
  </message>
  <message module="statistics">
    <id>weeks</id>
    <string>uger</string>
  </message>
  <message module="statistics">
    <id>Months: about</id>
    <string>M&aring;neder: ca.</string>
  </message>
  <message module="statistics">
    <id>months</id>
    <string>m&aring;neder</string>
  </message>
  <message module="statistics">
    <id>Years: about</id>
    <string>&aring;r: ca.</string>
  </message>
  <message module="statistics">
    <id>years</id>
    <string>&aring;r</string>
  </message>
  <message module="statistik">
    <id>Average Length</id>
    <string>Gennemsnitsl&aelig;ngde</string>
  </message>
  <message module="statistics">
    <id>Longest DVDs</id>
    <string>De l&aelig;ngste DVDer</string>
  </message>
  <message module="statistics">
    <id>Shortest DVDs</id>
    <string>De korteste DVDer</string>
  </message>
  <message module="statistics">
    <id>Regioncode</id>
    <string>Regions Kode</string>
  </message>
  <message module="statistics">
    <id>Localities of DVDs</id>
    <string>DVD Lokaliteter</string>
  </message>
  <message module="statistics">
    <id>Localities</id>
    <string>Lokaliteter</string>
  </message>
  <message module="statistics">
    <id>Origins of Movies</id>
    <string>Film oprindelse</string>
  </message>
  <message module="statistics">
    <id>Origins</id>
    <string>Oprindelse</string>
  </message>
  <message module="statistics">
    <id>Ratings</id>
    <string>Ratings</string>
  </message>
  <message module="statistics">
    <id>DVDs</id>
    <string>DVDer</string>
  </message>
  <message module="statistics">
    <id>Year of Purchase</id>
    <string>K&oslash;bs&aring;r</string>
  </message>
  <message module="statistics">
    <id>Detailed Statistic</id>
    <string>Detaljeret Statistik</string>
  </message>
  <message module="statistics">
    <id>total price</id>
    <string>Samlet pris</string>
  </message>
  <message module="statistics">
    <id>Production Decade</id>
    <string>Produktions &aring;rti</string>
  </message>
  <message module="statistics">
    <id>Place of Purchase (Top 10)</id>
    <string>K&oslash;bssted (Top 10)</string>
  </message>
  <message module="statistics">
    <id>Place of Purchase</id>
    <string>K&oslash;bssted</string>
  </message>
  <message module="statistics">
    <id>Genre (Top 10)</id>
    <string>Genre (Top 10)</string>
  </message>
  <message module="statistics">
    <id>Studio (Top 10)</id>
    <string>Studie (Top 10)</string>
  </message>
  <message module="statistics">
    <id>Media Companies (Top 10)</id>
    <string>Media Firmaer (Top 10)</string>
  </message>
  <message module="statistics">
    <id>Visitors</id>
    <string>Bes&oslash;gende</string>
  </message>
  <message module="statistics">
    <id>Visited DVDs</id>
    <string>Bes&oslash;gte DVD-Profiler</string>
  </message>

  <message module="statistics_graph">
    <id>owned</id>
    <string>Ejet</string>
  </message>
  <message module="statistics_graph">
    <id>ordered</id>
    <string>Bestilt</string>
  </message>
  <message module="statistics_graph">
    <id>wishlist</id>
    <string>&oslash;nskeliste</string>
  </message>

  <message module="statisticsdetail">
    <id>Visitor Statistic</id>
    <string>Bes&oslash;gende statistik</string>
  </message>
  <message module="statisticsdetail">
    <id>Profile Statistic</id>
    <string>Profil Statistik</string>
  </message>
  <message module="statisticsdetail">
    <id>Result</id>
    <string>Resultat</string>
  </message>
  <message module="statisticsdetail">
    <id>Month</id>
    <string>M&aring;ned</string>
  </message>
  <message module="statisticsdetail">
    <id>January</id>
    <string>Januar</string>
  </message>
  <message module="statisticsdetail">
    <id>February</id>
    <string>Februar</string>
  </message>
  <message module="statisticsdetail">
    <id>March</id>
    <string>Marts</string>
  </message>
  <message module="statisticsdetail">
    <id>May</id>
    <string>Maj</string>
  </message>
  <message module="statisticsdetail">
    <id>April</id>
    <string>April</string>
  </message>
  <message module="statisticsdetail">
    <id>June</id>
    <string>Juni</string>
  </message>
  <message module="statisticsdetail">
    <id>July</id>
    <string>Juli</string>
  </message>
  <message module="statisticsdetail">
    <id>August</id>
    <string>August</string>
  </message>
  <message module="statisticsdetail">
    <id>September</id>
    <string>September</string>
  </message>
  <message module="statisticsdetail">
    <id>October</id>
    <string>Oktober</string>
  </message>
  <message module="statisticsdetail">
    <id>November</id>
    <string>November</string>
  </message>
  <message module="statisticsdetail">
    <id>December</id>
    <string>December</string>
  </message>
  <message module="statisticsdetail">
    <id>Picture</id>
    <string>Billede</string>
  </message>
  <message module="statisticsdetail">
    <id>Writer/Screenwriter</id>
    <string>Forfatter</string>
  </message>

  <message module="news">
    <id>News Archive</id>
    <string>Nyhedsarkiv</string>
  </message>
  <message module="news">
    <id>Number of news</id>
    <string>Antal Nyheder</string>